In [13]:
## 加载数据集示例
import numpy as np
from DATA import Load_Data
## USPS数据集
data, target = Load_Data("USPS").Loading()
print("USPS", data.shape, len(target), len(np.unique(target)))

## bloodmnist数据集(格拉斯曼数据集)
data, target = Load_Data("bloodmnist").Load_MedMNIST()
print("bloodmnist", data.shape, len(target), len(np.unique(target)))

## ETH-80-10数据集(格拉斯曼数据集)
data, target = Load_Data("ETH-80-10").Loading()
print("ETH-80-10", data.shape, len(target), len(np.unique(target)))


USPS数据集加载完毕！          
USPS (11000, 256) 11000 10
bloodmnist数据集加载完毕！          
bloodmnist (17092, 2352) 17092 8
ETH-80-10数据集加载完毕！          
ETH-80-10 (80, 400, 10) 80 8


In [14]:
## 随机采样示例
import numpy as np
from DATA import Pre_Procession as pp
from DATA import Load_Data
data, target = Load_Data("USPS").Loading()
train_data, test_data, train_target, test_target = pp().uniform_sampling(data, target, train_size=10, random_state=517)
print(data.shape, train_data.shape, test_data.shape)

train_data, test_data, train_target, test_target = pp().uniform_sampling(data, target, train_size=0.1, random_state=517)
print(np.unique(target, return_counts=True)[1])
print(np.unique(train_target, return_counts=True)[1])
print(np.unique(test_target, return_counts=True)[1])

train_data, test_data, train_target, test_target = pp().sub_one_sampling(data, target, train_size=2, random_state=517)
print(np.unique(target, return_counts=True)[1])
print(np.unique(train_target, return_counts=True)[1])
print(np.unique(test_target, return_counts=True)[1])

USPS数据集加载完毕！          
(11000, 256) (100, 256) (10900, 256)
[1100 1100 1100 1100 1100 1100 1100 1100 1100 1100]
[110 110 110 110 110 110 110 110 110 110]
[990 990 990 990 990 990 990 990 990 990]
[1100 1100 1100 1100 1100 1100 1100 1100 1100 1100]
[1098 1098 1098 1098 1098 1098 1098 1098 1098 1098]
[2 2 2 2 2 2 2 2 2 2]
